name: Deploy to ankit_SB on Merge

on:
  push:
    branches:
      - deployment-changes-second-step

jobs:
    
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Salesforce CLI
      run: |
        npm install sfdx-cli --global
        sfdx --version

    - name: Authenticate to ankit_SB using Auth URL
      run: |
          echo "${{ secrets.ankit_SB_AUTH_URL }}" > auth.txt
          sfdx force:auth:sfdxurl:store -f auth.txt -a ankit_SB
          sfdx force:org:list
      shell: bash

    - name: Validate metadata deployment to ankit_SB
      run: |
        sfdx force:source:deploy -u ankit_SB -p force-app --checkonly --json --loglevel fatal
      shell: bash


    - name: Deploy metadata to Ankit_SB
      run: |
        sfdx force:source:deploy -u ankitdeployment-changes-second-step_SB -p force-app --json --loglevel fatal